# Generated by Django 3.2.9 on 2021-11-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESERVATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('END_DATE', models.DateField()),
                ('STATUS', models.SmallIntegerField(choices=[(0, 'Vacant'), (1, 'Reserved')], default=0)),
                ('RESERVED_BY', models.TextField(blank=True, null=True, verbose_name='RESERVED_BY')),
                ('START_DATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vacancy_limit')),
            ],
        ),
    ]
