# Generated by Django 3.2.9 on 2021-11-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='TOTAL_AMOUNT',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
